use_frameworks!

platform :ios, '9.0'

target 'YLDependencyCategories_Example' do
  pod 'YLDependencyCategories', :path => '../'
  

  target 'YLDependencyCategories_Tests' do
    inherit! :search_paths

    
  end
end
